name: fish AppImage

on:
  push:
    branches: [ main ]
    tags:
      - '*'           # Push events to every tag not containing /
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  installer-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        with:
          recipe: AppImageBuilder.yml

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: Continuous
          files: './fish*.AppImage*'
